# Generated by Django 3.2.3 on 2021-05-18 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_date_of_bird_author_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='gener',
            new_name='genrer',
        ),
    ]
