# Generated by Django 3.2.3 on 2021-05-18 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_rename_gener_book_genrer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='genrer',
            new_name='genre',
        ),
    ]
