# Generated by Django 3.2.3 on 2021-05-19 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_bookinstance_borrower'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='borrower',
            new_name='borrowed',
        ),
    ]
