# Generated by Django 3.2.3 on 2021-05-19 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_rename_borrowed_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set Book as returned'),)},
        ),
    ]
